### ISSUE TITLE
Failed when fetching dependency

### ISSUE THREAD

**Issue by taojigu** [richeterre/SwiftGoal#4]
gusdeMacBook-Pro-2:SwiftGoal gus$ carthage update
**\* Fetching Nimble
**\* Fetching Quick
**\* Fetching Curry
**\* Fetching Argo
**\* Fetching SnapKit
**\* Fetching ReactiveCocoa
**\* Fetching DZNEmptyDataSet
**\* Fetching Result
GitHub API request failed: NetworkError(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x7fe163715b00 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://api.github.com/repos/thoughtbot/Argo/releases/tags/v3.0.1?, NSErrorFailingURLKey=https://api.github.com/repos/thoughtbot/Argo/releases/tags/v3.0.1?, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.})

**Comment by cuongnguyenta** [comment]
If you have this problem. Please follow steps: 
1. Go to project folder - > Delete Cartfile, folder Cartfile, LICENSE and README.md 
2. Open terminal -> cd to folder project. 
3. Using command `touch Cartfile`.
4. Copy/Paste 
- github "dzenbot/DZNEmptyDataSet" == 1.8.1
- github "ReactiveCocoa/ReactiveCocoa" == 4.2.2
- github "SnapKit/SnapKit" == 0.21.1
- github "thoughtbot/Argo" == 3.1
- github "thoughtbot/Curry" == 2.3.3
- github "Quick/Quick" == 0.9.2
- github "Quick/Nimble" == 4.0.1

into Cartfile
5. Run command `carthage update --platform iOS`

Wait until finish. And the open project, it works well.
