### ISSUE TITLE
 Expression type 'SignalProducer<SignalProducer<Bool, NSError>, NoError>' is ambiguous without more context

### ISSUE THREAD

**Issue by AhmedAmineZribi** [richeterre/SwiftGoal#5]
I code with swift 3 and i'am using reactivecoacoa 5.0

 let viewIsVisible = SignalProducer<SignalProducer<Bool, NSError>, NoError>([
           reactive.base.viewWillAppear(true),
            reactive.base.viewWillDisappear(false)
            ]).flatten(.merge)

![capture d ecran 2017-02-23 a 1 12 12 am](https://cloud.githubusercontent.com/assets/15227156/23239042/2f565f9c-f965-11e6-920e-06ec80f2f11c.png)

**Comment by kpetroski** [comment]
Did you ever happen to figure this out?

**Comment by richeterre** [comment]
Closing this, as the project is unmaintained and won't support ReactiveCocoa 5. Hope you got it to work nevertheless! 🎈
